// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lppgjnlzqxydwvreylpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwcGdqbmx6cXh5ZHd2cmV5bHB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NDE2MDUsImV4cCI6MjA3OTExNzYwNX0.JSjm8L1j9V7dbqi8h6nbSt_YX0vxUyXFgfONxTbeBfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});